server:
    port: 8088

# 数据源配置
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
        username: root
        password: XuBin2020@
        driver-class-name: com.mysql.cj.jdbc.Driver
    quartz:
        job-store-type: JDBC #数据库存储quartz任务配置
        jdbc:
            initialize-schema: always #自动初始化表结构，第一次启动的时候这里写always
    #给项目来个名字
    application:
        name: rabbitmq-consumer
    #配置rabbitMq 服务器
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest
        #虚拟host 可以不设置,使用server默认host
        virtual-host: /

# MinIo文件服务器
minio:
    endpoint: http://124.222.49.29:9000
    accessKey: zimug
    secretKey: zimug-boot-launch

#日志位置配置
logging:
    config: classpath:logback.xml


